package com.kidoo.daily.domain.sec;

public class Role2Permission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_role_permission.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_role_permission.permission_id
     *
     * @mbggenerated
     */
    private Integer permissionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sec_role_permission.role_id
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_role_permission
     *
     * @mbggenerated
     */
    public Role2Permission(Integer id, Integer permissionId, Integer roleId) {
        this.id = id;
        this.permissionId = permissionId;
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_role_permission
     *
     * @mbggenerated
     */
    public Role2Permission() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_role_permission.id
     *
     * @return the value of sec_role_permission.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_role_permission.id
     *
     * @param id the value for sec_role_permission.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_role_permission.permission_id
     *
     * @return the value of sec_role_permission.permission_id
     *
     * @mbggenerated
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_role_permission.permission_id
     *
     * @param permissionId the value for sec_role_permission.permission_id
     *
     * @mbggenerated
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sec_role_permission.role_id
     *
     * @return the value of sec_role_permission.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sec_role_permission.role_id
     *
     * @param roleId the value for sec_role_permission.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}