package com.kidoo.daily.domain.test;

public class IProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_product.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_product.front_product_id
     *
     * @mbggenerated
     */
    private String frontProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_product.core_product_id
     *
     * @mbggenerated
     */
    private String coreProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_product.reserve001
     *
     * @mbggenerated
     */
    private String reserve001;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_product.reserve002
     *
     * @mbggenerated
     */
    private String reserve002;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_product.reserve003
     *
     * @mbggenerated
     */
    private String reserve003;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_product.reserve004
     *
     * @mbggenerated
     */
    private String reserve004;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_product
     *
     * @mbggenerated
     */
    public IProduct(Integer id, String frontProductId, String coreProductId, String reserve001, String reserve002, String reserve003, String reserve004) {
        this.id = id;
        this.frontProductId = frontProductId;
        this.coreProductId = coreProductId;
        this.reserve001 = reserve001;
        this.reserve002 = reserve002;
        this.reserve003 = reserve003;
        this.reserve004 = reserve004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_product
     *
     * @mbggenerated
     */
    public IProduct() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_product.id
     *
     * @return the value of i_product.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_product.id
     *
     * @param id the value for i_product.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_product.front_product_id
     *
     * @return the value of i_product.front_product_id
     *
     * @mbggenerated
     */
    public String getFrontProductId() {
        return frontProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_product.front_product_id
     *
     * @param frontProductId the value for i_product.front_product_id
     *
     * @mbggenerated
     */
    public void setFrontProductId(String frontProductId) {
        this.frontProductId = frontProductId == null ? null : frontProductId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_product.core_product_id
     *
     * @return the value of i_product.core_product_id
     *
     * @mbggenerated
     */
    public String getCoreProductId() {
        return coreProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_product.core_product_id
     *
     * @param coreProductId the value for i_product.core_product_id
     *
     * @mbggenerated
     */
    public void setCoreProductId(String coreProductId) {
        this.coreProductId = coreProductId == null ? null : coreProductId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_product.reserve001
     *
     * @return the value of i_product.reserve001
     *
     * @mbggenerated
     */
    public String getReserve001() {
        return reserve001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_product.reserve001
     *
     * @param reserve001 the value for i_product.reserve001
     *
     * @mbggenerated
     */
    public void setReserve001(String reserve001) {
        this.reserve001 = reserve001 == null ? null : reserve001.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_product.reserve002
     *
     * @return the value of i_product.reserve002
     *
     * @mbggenerated
     */
    public String getReserve002() {
        return reserve002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_product.reserve002
     *
     * @param reserve002 the value for i_product.reserve002
     *
     * @mbggenerated
     */
    public void setReserve002(String reserve002) {
        this.reserve002 = reserve002 == null ? null : reserve002.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_product.reserve003
     *
     * @return the value of i_product.reserve003
     *
     * @mbggenerated
     */
    public String getReserve003() {
        return reserve003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_product.reserve003
     *
     * @param reserve003 the value for i_product.reserve003
     *
     * @mbggenerated
     */
    public void setReserve003(String reserve003) {
        this.reserve003 = reserve003 == null ? null : reserve003.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_product.reserve004
     *
     * @return the value of i_product.reserve004
     *
     * @mbggenerated
     */
    public String getReserve004() {
        return reserve004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_product.reserve004
     *
     * @param reserve004 the value for i_product.reserve004
     *
     * @mbggenerated
     */
    public void setReserve004(String reserve004) {
        this.reserve004 = reserve004 == null ? null : reserve004.trim();
    }
}