package com.kidoo.daily.domain.test;

public class TCorrect {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_correct.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_correct.already_times
     *
     * @mbggenerated
     */
    private Integer alreadyTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_correct.sentences
     *
     * @mbggenerated
     */
    private String sentences;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_correct.success
     *
     * @mbggenerated
     */
    private Integer success;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_correct.reserve001
     *
     * @mbggenerated
     */
    private String reserve001;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_correct.reserve002
     *
     * @mbggenerated
     */
    private String reserve002;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_correct.reserve003
     *
     * @mbggenerated
     */
    private String reserve003;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_correct
     *
     * @mbggenerated
     */
    public TCorrect(Integer id, Integer alreadyTimes, String sentences, Integer success, String reserve001, String reserve002, String reserve003) {
        this.id = id;
        this.alreadyTimes = alreadyTimes;
        this.sentences = sentences;
        this.success = success;
        this.reserve001 = reserve001;
        this.reserve002 = reserve002;
        this.reserve003 = reserve003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_correct
     *
     * @mbggenerated
     */
    public TCorrect() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_correct.id
     *
     * @return the value of t_correct.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_correct.id
     *
     * @param id the value for t_correct.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_correct.already_times
     *
     * @return the value of t_correct.already_times
     *
     * @mbggenerated
     */
    public Integer getAlreadyTimes() {
        return alreadyTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_correct.already_times
     *
     * @param alreadyTimes the value for t_correct.already_times
     *
     * @mbggenerated
     */
    public void setAlreadyTimes(Integer alreadyTimes) {
        this.alreadyTimes = alreadyTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_correct.sentences
     *
     * @return the value of t_correct.sentences
     *
     * @mbggenerated
     */
    public String getSentences() {
        return sentences;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_correct.sentences
     *
     * @param sentences the value for t_correct.sentences
     *
     * @mbggenerated
     */
    public void setSentences(String sentences) {
        this.sentences = sentences == null ? null : sentences.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_correct.success
     *
     * @return the value of t_correct.success
     *
     * @mbggenerated
     */
    public Integer getSuccess() {
        return success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_correct.success
     *
     * @param success the value for t_correct.success
     *
     * @mbggenerated
     */
    public void setSuccess(Integer success) {
        this.success = success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_correct.reserve001
     *
     * @return the value of t_correct.reserve001
     *
     * @mbggenerated
     */
    public String getReserve001() {
        return reserve001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_correct.reserve001
     *
     * @param reserve001 the value for t_correct.reserve001
     *
     * @mbggenerated
     */
    public void setReserve001(String reserve001) {
        this.reserve001 = reserve001 == null ? null : reserve001.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_correct.reserve002
     *
     * @return the value of t_correct.reserve002
     *
     * @mbggenerated
     */
    public String getReserve002() {
        return reserve002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_correct.reserve002
     *
     * @param reserve002 the value for t_correct.reserve002
     *
     * @mbggenerated
     */
    public void setReserve002(String reserve002) {
        this.reserve002 = reserve002 == null ? null : reserve002.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_correct.reserve003
     *
     * @return the value of t_correct.reserve003
     *
     * @mbggenerated
     */
    public String getReserve003() {
        return reserve003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_correct.reserve003
     *
     * @param reserve003 the value for t_correct.reserve003
     *
     * @mbggenerated
     */
    public void setReserve003(String reserve003) {
        this.reserve003 = reserve003 == null ? null : reserve003.trim();
    }
}